sudo: true

install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.42.2/hugo_0.42.2_Linux-64bit.deb
- sudo dpkg -i hugo_0.42.2_Linux-64bit.deb

script:
- hugo version
- hugo -D

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
