baseURL = "https://dashdashzako.github.io/poppy-station/"
languageCode = "fr"
title = "Poppy Station"
theme = "poppy-station"
disableKinds = ["taxonomy", "taxonomyTerm"]

enableRobotsTXT = true

[permalinks]
page = "/:slug/"
articles = "/:sections/:year/:slug/"

[params]

company = "Poppy Station"

[params.jumbotron]
title = "Poppy Station"
description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Est accusantium, dolore, possimus sint odit voluptatum quia optio sed dignissimos iste cumque cupiditate aut quasi reprehenderit quae repellat nulla vero vitae."

[params.contactForm]
email = "junk@dashdashzako.net"
