baseURL = "https://poppy-project.github.io/poppystation.org/"
languageCode = "fr"
title = "Poppy Station"
theme = "poppy-station"
disableKinds = ["taxonomy", "taxonomyTerm"]

enableRobotsTXT = true

[permalinks]
page = "/:slug/"
articles = "/:sections/:year/:slug/"

[params]

company = "Poppy Station" 

[params.jumbotron]
title = "Poppy Station"
description = "Ecosystème Poppy d'innovation robotique et IA pour l'éducation, les arts et la recherche"

[params.contactForm]
email = "junk@dashdashzako.net"
